// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// TRACommandAddin2.h
// Provide implementation to interface
//    CATIAfrGeneralWksAddin

//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//EXTENSION:	TRAECommandAddin2
//EXTENSIONTYPE:	DataExtension

//    TIE: CATIAfrGeneralWksAddin

//End CAA2 Wizard Generation Report
//
//  Jun 2022  Creation: Code generated by the CAA wizard  Dell
//===================================================================
#ifndef TRACommandAddin2_H
#define TRACommandAddin2_H

#include "TRACommandAddinMod.h"
#include "CATBaseUnknown.h"

class CATCmdContainer;

//-----------------------------------------------------------------------

/**
* Class representing xxx.
*
* <br><b>Role</b>: Provide the basic class function...
* <p>
* It implements the interfaces :
*  <ol>
*  <li>@href CATIAfrGeneralWksAddin
*  </ol>
*
* @href ClassReference, Class#MethodReference, #InternalMethod...
*/
class ExportedByTRACommandAddinMod TRACommandAddin2: public CATBaseUnknown

{
  CATDeclareClass;

  public:

	  public:

	    // Instantiates the command headers for the commands
     void CreateCommands();

     // Creates toolbars and arranges the commands inside
    

  // Standard constructors and destructors for an implementation class
  // -----------------------------------------------------------------
     TRACommandAddin2 ();
     virtual ~TRACommandAddin2 ();


  private:
  // The copy constructor and the equal operator must not be implemented
  // -------------------------------------------------------------------
  TRACommandAddin2 (TRACommandAddin2 &);
  TRACommandAddin2& operator=(TRACommandAddin2&);

};

//-----------------------------------------------------------------------

#endif
