// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// TRAStCommand.h
// The state chart based command: TRAStCommand
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Jun 2022  Creation: Code generated by the CAA wizard  Dell
//===================================================================
#ifndef TRAStCommand_H
#define TRAStCommand_H

#include "TRAStCommandMod.h"
#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "CATIGSMTool.h"  
#include "CATIGSMFactory.h"
#include "CATIPrtPart.h"
#include "CATIPrtContainer.h"
#include "CATIGSMPoint.h"
#include "CATIProduct.h"






class CATIndicationAgent;

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class ExportedByTRAStCommandMod TRAStCommand: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( TRAStCommand, CATStateCommand )

  public:

	  HRESULT AddExternalComponent(CATIProduct *iThisProd, CATDocument *iDocument, CATIProduct **oNewProduct);

	  HRESULT AddNewExternalComponent(CATIProduct* iThisProd, const CATUnicodeString iDocumentType,const CATUnicodeString iPartNumber, CATIProduct** oNewProduct);

  TRAStCommand();
  virtual ~TRAStCommand();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();

    /**
     * Action associated to state transitions.
     */
 // virtual CATBoolean  ActionOne(void * data);

  private:

	
};

//----------------------------------------------------------------------

#endif
