// COPYRIGHT Dassault Systemes 2022
//===================================================================
//
// TRAStCommand.h
// The state chart based command: TRAStCommand
//
//===================================================================
//
// Usage notes:
//
//===================================================================
//CAA2 Wizard Generation Report
//   STATECOMMAND
//End CAA2 Wizard Generation Report
//
//  Jun 2022  Creation: Code generated by the CAA wizard  Dell
//===================================================================
#ifndef TRAStCommand_H
#define TRAStCommand_H

#include "TRAStCommandMod.h"
#include "CATStateCommand.h"
#include "CATBoolean.h"
#include "CATIGSMTool.h"  
#include "CATIGSMFactory.h"
#include "CATIPrtPart.h"
#include "CATIPrtContainer.h"
#include "CATIGSMPoint.h"





class CATIndicationAgent;

//----------------------------------------------------------------------

/**
 * Describe your command here.
 * <p>
 * Using this prefered syntax will enable mkdoc to document your class.
 * <p>
 * refer to programming resources of Dialog engine framework.
 * (consult base class description).
 */
class ExportedByTRAStCommandMod TRAStCommand: public CATStateCommand
{
  // Allows customization/internationalization of command's messages
  // ---------------------------------------------------------------
  DeclareResource( TRAStCommand, CATStateCommand )

  public:

	  CATIGSMTool_var  CreateGSMTool(const CATUnicodeString& iName,int iSetAsCurrent, int iTopLevel, int iType );

	  void InsertInProceduralView(CATISpecObject_var &ispSpecObject);

	  CATIGSMPoint_var CreatePoint( double cord[3] ) ;

	  CATISpecObject_var CreateLinePtPt(CATLISTV(CATISpecObject_var) &iaObjectsParam);

  TRAStCommand();
  virtual ~TRAStCommand();

    /**
     * Defines the command automata.
     * <br>
     * <i>(states, transitions and agents)</i>
     */
  virtual void     BuildGraph();

    /**
     * Action associated to state transitions.
     */
  virtual CATBoolean  ActionOne(void * data);

  private:

	  CATIGSMFactory * _pFact ;

	  CATIPrtPart_var    _spPart;

	  CATIPrtContainer_var          _spPartCont ;

	  CATBaseUnknown_var _spMainPartBody ;

  CATIndicationAgent	* _Indication;

  CATIGSMFactory_var _spGSMFactory;
};

//----------------------------------------------------------------------

#endif
